CREATE TABLE Categories (
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE Items (
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(30) NOT NULL,
	Price DECIMAL(18, 2) NOT NULL,
	CategoryId INT FOREIGN KEY REFERENCES Categories(Id)
)

CREATE TABLE Employees (
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Phone CHAR(12) NOT NULL,
	Salary DECIMAL(18, 2) NOT NULL
)

CREATE TABLE Orders (
	Id INT PRIMARY KEY IDENTITY,
	[DateTime] DATETIME NOT NULL,
	EmployeeId INT FOREIGN KEY REFERENCES Employees(Id)
)

CREATE TABLE OrderItems (
	OrderId INT FOREIGN KEY REFERENCES Orders(Id),
	ItemId INT FOREIGN KEY REFERENCES Items(Id),
	Quantity INT CHECK(Quantity >= 1) NOT NULL,

	CONSTRAINT PK_OrdersItems PRIMARY KEY(OrderId, ItemId)
)

CREATE TABLE Shifts (
	Id INT IDENTITY,
	EmployeeId INT FOREIGN KEY REFERENCES Employees(Id),
	CheckIn DATETIME NOT NULL,
	CheckOut DATETIME NOT NULL,

	CONSTRAINT CK_CheckOutAfterCheckIn CHECK (CheckOut > CheckIn),
	CONSTRAINT PK_Shifts PRIMARY KEY(Id, EmployeeId)
)